### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by emeryberger** [conda-forge/scalene-feedstock#10]
### Comment:

Hi all @jakirkham @carterbox - I'd like to support Windows users with conda but I don't know how (the Windows version doesn't require a build). Any help would be most appreciated!

**Comment by jakirkham** [comment]
Would drop this line and [re-render]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks )

https://github.com/conda-forge/scalene-feedstock/blob/c647bb549102b26971b09a014a1228f1530b61af/recipe/meta.yaml#L15

Separately we can drop [this file]( https://github.com/conda-forge/scalene-feedstock/blob/c647bb549102b26971b09a014a1228f1530b61af/recipe/build.bat ) as this is already handled with [this `script` line]( https://github.com/conda-forge/scalene-feedstock/blob/c647bb549102b26971b09a014a1228f1530b61af/recipe/meta.yaml#L17 )

**Comment by emeryberger** [comment]
OK, this clearly just reflected a misunderstanding on my part about the semantics of build - will do, thanks!

**Comment by carterbox** [comment]
@emeryberger. Do not push commits directly to the feedstock. [Open a PR from a personal fork](https://github.com/conda-forge/scalene-feedstock#updating-scalene-feedstock)!

**Comment by emeryberger** [comment]
Sorry! Will do!

**Comment by emeryberger** [comment]
Windows still not showing up...

**Comment by jakirkham** [comment]
Please see comment ( https://github.com/conda-forge/scalene-feedstock/pull/11#issuecomment-1319241397 )

**Comment by emeryberger** [comment]
Works now!
