### ISSUE TITLE
Python 3.8 builds failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/scalene-feedstock#41]
The Python 3.8 jobs are seeing failures like [this job]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=916441&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=ecca2736-6363-55be-133f-faae951bb9b5&l=844 ). Snippet below:

```cpp
 In file included from src/source/libscalene.cpp:93:
  /home/conda/feedstock_root/build_artifacts/scalene_1713294069178/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/python3.8/Python.h:44:10: fatal error: crypt.h: No such file or directory
     44 | #include <crypt.h>
        |          ^~~~~~~~~
  compilation terminated.
```

Likely a result of upstream changes ( https://github.com/conda-forge/linux-sysroot-feedstock/issues/52 )

Fixing probably involves updating the include search paths

That said, Python 3.8 will be [EOL'd October 2024]( https://devguide.python.org/versions/ ). So maybe it is easier to just drop it now

**Comment by emeryberger** [comment]
Thanks - I was wondering what was going wrong. I've removed it from the build.

**Comment by jakirkham** [comment]
Ok after some discussion with a couple colleagues and a closer look at the build system, think we may want to make some tweaks to how scalene builds. This is independent of whether Python 3.8 is supported as it is relevant for all builds. Have raised an upstream issue ( https://github.com/plasma-umass/scalene/issues/812 ) to discuss how we might want to approach this
