### ISSUE TITLE
Incorrect pynvml dependency

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/scalene-feedstock#44]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For several builds now, the upstream version of this package has supported pynvml 11.5.  However, this package continues to list pynvml <11.5 as a dependency.  I would just submit a PR to address this issue.  However, since this package has also dropped support for Python 3.8, I would also appreciate if an appropriate build supporting pynvml 11.5 could also be made for Python 3.8, which may mean another build of v1.5.39.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by DManowitz** [comment]
@emeryberger @jaltmayerpizzorno @sternj  Checking in on this issue.  Any thoughts?

**Comment by jakirkham** [comment]
It might be worth moving to `nvidia-ml-py`, which superseded `pynvml` (with a couple features dropped)

`nvidia-ml-py` is continuing to get regular updates; whereas, `pynvml` is not

Admittedly this may involve upstream changes

**Comment by emeryberger** [comment]
I just verified that `nvidia-ml-py` works on a recent-ish NVIDIA GPU, and have switched to that. I'll cut a new release momentarily.

**Comment by emeryberger** [comment]
Closing as `nvidia-ml-py` will be the NVIDIA GPU library going forwards.
