### ISSUE TITLE
Using lower case for `jinja2` dependency

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/scalene-feedstock#9]
The package name [`jinja2`]( https://github.com/conda-forge/jinja2-feedstock ) is lower cased. Currently the requirements has `Jinja2` specified. Would be good to match the naming convention here.

https://github.com/conda-forge/scalene-feedstock/blob/7709aee675f6269d2db6b019b27c4777bb20312b/recipe/meta.yaml#L36

**Comment by emeryberger** [comment]
Done, thanks.
